version: '3'
services:
  db-ajax:
    image: postgres
    container_name: db-ajax
    env_file: .env
  web-ajax:
    build: .
    container_name: web-ajax
    command: bundle exec "rails s -b 0.0.0.0"
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
    links:
      - db-ajax
